// src/config/workflowConfig.js
const WORKFLOW_CONFIG = {
  reception: {
    socketRoom: "reception",
    endpointKey: "receptionWorkflow",
    columns: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client ID" },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "method_received", label: "Method Received" },
    ],
    columnsExpanded: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client ID" },
      { name: "batch_size", label: "Batch Size" },
      { name: "method_received", label: "Method Received" },
      { name: "bank_statements", label: "Bank Statements", formatter: (val) => (val ? "Yes" : "No") },
      { name: "synaps", label: "Synaps" },
      { name: "total_urgent_foreign", label: "Total Urgent Foreign" },
      { name: "cc_availability", label: "CC Availability" },
      { name: "current_department", label: "Current Department" },
      { name: "status", label: "Status" },
      { name: "batch_total", label: "Batch Total", formatter: (val) => `$${val?.toFixed(2) || "0.00"}` },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "date_completed", label: "Date Completed", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "created_by", label: "Created By" },
      { name: "admitted_by", label: "Admitted By" },
      { name: "billed_by", label: "Billed By" },
      { name: "completed_by", label: "Completed By" },
      { name: "date_checked", label: "Date Checked", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "checked_by", label: "Checked By" },
      { name: "errors", label: "Errors" },
      { name: "billing_emailed_by", label: "Billing Emailed By" },
      { name: "file_renamed_by", label: "File Renamed By" },
      { name: "file_checked_by", label: "File Checked By" },
      { name: "filed_by", label: "Filed By" },
      { name: "notes", label: "Notes" },
      { name: "billing_email_sent_by", label: "Billing Email Sent By" },
      { name: "added_on_drive", label: "Added on Drive", formatter: (val) => (val ? "Yes" : "No") },
      { name: "corrections", label: "Corrections", formatter: (val) => (val ? "Yes" : "No") },
      { name: "is_pure_foreign_urgent", label: "Is Pure Foreign Urgent", formatter: (val) => (val ? "Yes" : "No") },
      { name: "created_at", label: "Created At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "updated_at", label: "Updated At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
    ],
    foreignUrgentColumns: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client ID" },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "method_received", label: "Method Received" },
      { name: "patient_name", label: "Patient Name" },
      { name: "medical_aid_nr", label: "Medical Aid Number" },
    ],
    foreignUrgentColumnsExpanded: [
      { name: "foreign_urgent_batch_id", label: "Foreign Urgent Batch ID" },
      { name: "batch_id", label: "Parent Batch ID" },
      { name: "patient_name", label: "Patient Name" },
      { name: "medical_aid_nr", label: "Medical Aid Number" },
      { name: "current_department", label: "Current Department" },
      { name: "status", label: "Status" },
      { name: "created_by", label: "Created By" },
      { name: "admitted_by", label: "Admitted By" },
      { name: "billed_by", label: "Billed By" },
      { name: "completed_by", label: "Completed By" },
      { name: "date_checked", label: "Date Checked", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "checked_by", label: "Checked By" },
      { name: "errors", label: "Errors" },
      { name: "file_renamed", label: "File Renamed", formatter: (val) => (val ? "Yes" : "No") },
      { name: "file_renamed_by", label: "File Renamed By" },
      { name: "file_checked", label: "File Checked", formatter: (val) => (val ? "Yes" : "No") },
      { name: "file_checked_by", label: "File Checked By" },
      { name: "filed_by", label: "Filed By" },
      { name: "notes", label: "Notes" },
      { name: "FULID", label: "FULID" },
      { name: "created_at", label: "Created At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "updated_at", label: "Updated At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      // Inherited from batches
      { name: "client_id", label: "Client ID" },
      { name: "method_received", label: "Method Received" },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "bank_statements", label: "Bank Statements", formatter: (val) => (val ? "Yes" : "No") },
      { name: "added_on_drive", label: "Added on Drive", formatter: (val) => (val ? "Yes" : "No") },
      { name: "cc_availability", label: "CC Availability" },
      { name: "corrections", label: "Corrections", formatter: (val) => (val ? "Yes" : "No") },
    ],
    mainActions: [
      {
        name: "sentToAdmittance",
        label: "Send to Admittance",
        method: "post",
        endpointKey: "moveToAdmittance",
      },
    ],
    actions: [
      {
        name: "sentToBilling",
        label: "Send to Billing",
        method: "post",
        endpointKey: "moveToBilling",
      },
    ],
    tables: [
      { name: "inbox" },
      { name: "current" },
      { name: "outbox" },
      { name: "filing" },
    ],
  },
  admittance: {
    socketRoom: "admittance",
    endpointKey: "admittanceWorkflow",
    columns: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client ID" },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "method_received", label: "Method Received" },
    ],
    columnsExpanded: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client ID" },
      { name: "batch_size", label: "Batch Size" },
      { name: "method_received", label: "Method Received" },
      { name: "bank_statements", label: "Bank Statements", formatter: (val) => (val ? "Yes" : "No") },
      { name: "synaps", label: "Synaps" },
      { name: "total_urgent_foreign", label: "Total Urgent Foreign" },
      { name: "cc_availability", label: "CC Availability" },
      { name: "current_department", label: "Current Department" },
      { name: "status", label: "Status" },
      { name: "batch_total", label: "Batch Total", formatter: (val) => `$${val?.toFixed(2) || "0.00"}` },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "date_completed", label: "Date Completed", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "created_by", label: "Created By" },
      { name: "admitted_by", label: "Admitted By" },
      { name: "billed_by", label: "Billed By" },
      { name: "completed_by", label: "Completed By" },
      { name: "date_checked", label: "Date Checked", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "checked_by", label: "Checked By" },
      { name: "errors", label: "Errors" },
      { name: "billing_emailed_by", label: "Billing Emailed By" },
      { name: "file_renamed_by", label: "File Renamed By" },
      { name: "file_checked_by", label: "File Checked By" },
      { name: "filed_by", label: "Filed By" },
      { name: "notes", label: "Notes" },
      { name: "billing_email_sent_by", label: "Billing Email Sent By" },
      { name: "added_on_drive", label: "Added on Drive", formatter: (val) => (val ? "Yes" : "No") },
      { name: "corrections", label: "Corrections", formatter: (val) => (val ? "Yes" : "No") },
      { name: "is_pure_foreign_urgent", label: "Is Pure Foreign Urgent", formatter: (val) => (val ? "Yes" : "No") },
      { name: "created_at", label: "Created At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "updated_at", label: "Updated At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
    ],
    foreignUrgentColumns: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client ID" },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "method_received", label: "Method Received" },
      { name: "patient_name", label: "Patient Name" },
      { name: "medical_aid_nr", label: "Medical Aid Number" },
    ],
    foreignUrgentColumnsExpanded: [
      { name: "foreign_urgent_batch_id", label: "Foreign Urgent Batch ID" },
      { name: "batch_id", label: "Parent Batch ID" },
      { name: "patient_name", label: "Patient Name" },
      { name: "medical_aid_nr", label: "Medical Aid Number" },
      { name: "current_department", label: "Current Department" },
      { name: "status", label: "Status" },
      { name: "created_by", label: "Created By" },
      { name: "admitted_by", label: "Admitted By" },
      { name: "billed_by", label: "Billed By" },
      { name: "completed_by", label: "Completed By" },
      { name: "date_checked", label: "Date Checked", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "checked_by", label: "Checked By" },
      { name: "errors", label: "Errors" },
      { name: "file_renamed", label: "File Renamed", formatter: (val) => (val ? "Yes" : "No") },
      { name: "file_renamed_by", label: "File Renamed By" },
      { name: "file_checked", label: "File Checked", formatter: (val) => (val ? "Yes" : "No") },
      { name: "file_checked_by", label: "File Checked By" },
      { name: "filed_by", label: "Filed By" },
      { name: "notes", label: "Notes" },
      { name: "FULID", label: "FULID" },
      { name: "created_at", label: "Created At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "updated_at", label: "Updated At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "client_id", label: "Client ID" },
      { name: "method_received", label: "Method Received" },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "bank_statements", label: "Bank Statements", formatter: (val) => (val ? "Yes" : "No") },
      { name: "added_on_drive", label: "Added on Drive", formatter: (val) => (val ? "Yes" : "No") },
      { name: "cc_availability", label: "CC Availability" },
      { name: "corrections", label: "Corrections", formatter: (val) => (val ? "Yes" : "No") },
    ],
    mainActions: [
      {
        name: "sentToBilling",
        label: "Admit",
        method: "post",
        endpointKey: "moveToBilling",
      },
    ],
    actions: [
      {
        name: "sentToReception",
        label: "Send to Reception",
        method: "post",
        endpointKey: "moveToReception",
      },
      {
        name: "sentToBilling",
        label: "Send to Billing",
        method: "post",
        endpointKey: "moveToBilling",
      },
    ],
    tables: [
      { name: "inbox" },
      { name: "current" },
      { name: "outbox" },
    ],
  },
  billing: {
    socketRoom: "billing",
    endpointKey: "billingWorkflow",
    columns: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client ID" },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "method_received", label: "Method Received" },
    ],
    columnsExpanded: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client ID" },
      { name: "batch_size", label: "Batch Size" },
      { name: "method_received", label: "Method Received" },
      { name: "bank_statements", label: "Bank Statements", formatter: (val) => (val ? "Yes" : "No") },
      { name: "synaps", label: "Synaps" },
      { name: "total_urgent_foreign", label: "Total Urgent Foreign" },
      { name: "cc_availability", label: "CC Availability" },
      { name: "current_department", label: "Current Department" },
      { name: "status", label: "Status" },
      { name: "batch_total", label: "Batch Total", formatter: (val) => `$${val?.toFixed(2) || "0.00"}` },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "date_completed", label: "Date Completed", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "created_by", label: "Created By" },
      { name: "admitted_by", label: "Admitted By" },
      { name: "billed_by", label: "Billed By" },
      { name: "completed_by", label: "Completed By" },
      { name: "date_checked", label: "Date Checked", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "checked_by", label: "Checked By" },
      { name: "errors", label: "Errors" },
      { name: "billing_emailed_by", label: "Billing Emailed By" },
      { name: "file_renamed_by", label: "File Renamed By" },
      { name: "file_checked_by", label: "File Checked By" },
      { name: "filed_by", label: "Filed By" },
      { name: "notes", label: "Notes" },
      { name: "billing_email_sent_by", label: "Billing Email Sent By" },
      { name: "added_on_drive", label: "Added on Drive", formatter: (val) => (val ? "Yes" : "No") },
      { name: "corrections", label: "Corrections", formatter: (val) => (val ? "Yes" : "No") },
      { name: "is_pure_foreign_urgent", label: "Is Pure Foreign Urgent", formatter: (val) => (val ? "Yes" : "No") },
      { name: "created_at", label: "Created At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "updated_at", label: "Updated At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
    ],
    foreignUrgentColumns: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client ID" },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "method_received", label: "Method Received" },
      { name: "patient_name", label: "Patient Name" },
      { name: "medical_aid_nr", label: "Medical Aid Number" },
    ],
    foreignUrgentColumnsExpanded: [
      { name: "foreign_urgent_batch_id", label: "Foreign Urgent Batch ID" },
      { name: "batch_id", label: "Parent Batch ID" },
      { name: "patient_name", label: "Patient Name" },
      { name: "medical_aid_nr", label: "Medical Aid Number" },
      { name: "current_department", label: "Current Department" },
      { name: "status", label: "Status" },
      { name: "created_by", label: "Created By" },
      { name: "admitted_by", label: "Admitted By" },
      { name: "billed_by", label: "Billed By" },
      { name: "completed_by", label: "Completed By" },
      { name: "date_checked", label: "Date Checked", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "checked_by", label: "Checked By" },
      { name: "errors", label: "Errors" },
      { name: "file_renamed", label: "File Renamed", formatter: (val) => (val ? "Yes" : "No") },
      { name: "file_renamed_by", label: "File Renamed By" },
      { name: "file_checked", label: "File Checked", formatter: (val) => (val ? "Yes" : "No") },
      { name: "file_checked_by", label: "File Checked By" },
      { name: "filed_by", label: "Filed By" },
      { name: "notes", label: "Notes" },
      { name: "FULID", label: "FULID" },
      { name: "created_at", label: "Created At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "updated_at", label: "Updated At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "client_id", label: "Client ID" },
      { name: "method_received", label: "Method Received" },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "bank_statements", label: "Bank Statements", formatter: (val) => (val ? "Yes" : "No") },
      { name: "added_on_drive", label: "Added on Drive", formatter: (val) => (val ? "Yes" : "No") },
      { name: "cc_availability", label: "CC Availability" },
      { name: "corrections", label: "Corrections", formatter: (val) => (val ? "Yes" : "No") },
    ],
    actions: [
      {
        name: "sentToReception",
        label: "Send to Reception",
        method: "post",
        endpointKey: "moveToReception",
      },
      {
        name: "sentToAdmittance",
        label: "Send to Admittance",
        method: "post",
        endpointKey: "moveToAdmittance",
      },
    ],
    tables: [
      { name: "inbox" },
      { name: "current" },
      { name: "outbox" },
    ],
  },
};

export default WORKFLOW_CONFIG;