// src/config/workflowConfig.js
const formatCurrency = (val) => {
  const num = Number(val);
  if (Number.isFinite(num)) return `R${num.toFixed(2)}`;
  return 'R0.00';
};

const WORKFLOW_CONFIG = {
  reception: {
    socketRoom: "reception",
    endpointKey: "receptionWorkflow",
    columns: [
      { name: "batch_id", label: "Batch ID" },
      { name: "batch_size", label: "Batch Size" },
      { name: "client_id", label: "Client", formatter: (val, row) => (row.client_first || row.client_last) ? (`Dr ${row.client_first || ''} ${row.client_last || ''}`).trim() : val },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "method_received", label: "Method Received" },
      { name: "bank_statements", label: "Bank Statements", formatter: (val) => (val ? "Yes" : "No") },
      { name: "added_on_drive", label: "Added on Drive", formatter: (val) => (val ? "Yes" : "No") },
      { name: "corrections", label: "Corrections", formatter: (val) => (val ? "Yes" : "No") },
      { name: "cc_availability", label: "CC Availability" },
    ],
    columnsExpanded: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client", formatter: (val, row) => (row.client_first || row.client_last) ? (`Dr ${row.client_first || ''} ${row.client_last || ''}`).trim() : val },
      { name: "batch_size", label: "Batch Size" },
      { name: "method_received", label: "Method Received" },
      { name: "bank_statements", label: "Bank Statements", formatter: (val) => (val ? "Yes" : "No") },
      { name: "synaps", label: "Synaps" },
      { name: "total_urgent_foreign", label: "Total Urgent Foreign" },
      { name: "cc_availability", label: "CC Availability" },
      { name: "current_department", label: "Current Department" },
      { name: "status", label: "Status" },
      { name: "batch_total", label: "Batch Total", formatter: (val) => formatCurrency(val) },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "date_completed", label: "Date Completed", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "created_by", label: "Created By", formatter: (val, row) => row.created_by_name ?? val },
      { name: "admitted_by", label: "Admitted By", formatter: (val, row) => row.admitted_by_name ?? val },
      { name: "billed_by", label: "Billed By", formatter: (val, row) => row.billed_by_name ?? val },
      { name: "completed_by", label: "Completed By" },
      { name: "date_checked", label: "Date Checked", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "checked_by", label: "Checked By" },
      { name: "errors", label: "Errors" },
      { name: "billing_emailed_by", label: "Billing Emailed By" },
      { name: "file_renamed_by", label: "File Renamed By" },
      { name: "file_checked_by", label: "File Checked By" },
      { name: "filed_by", label: "Filed By" },
      { name: "notes", label: "Notes" },
      { name: "billing_email_sent_by", label: "Billing Email Sent By" },
      { name: "added_on_drive", label: "Added on Drive", formatter: (val) => (val ? "Yes" : "No") },
      { name: "corrections", label: "Corrections", formatter: (val) => (val ? "Yes" : "No") },
      { name: "is_pure_foreign_urgent", label: "Is Pure Foreign Urgent", formatter: (val) => (val ? "Yes" : "No") },
      { name: "created_at", label: "Created At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "updated_at", label: "Updated At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
    ],
    foreignUrgentColumns: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client", formatter: (val, row) => (row.client_first || row.client_last) ? (`Dr ${row.client_first || ''} ${row.client_last || ''}`).trim() : val },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "method_received", label: "Method Received" },
      { name: "patient_name", label: "Patient Name" },
      { name: "medical_aid_nr", label: "Medical Aid Number" },
    ],
    foreignUrgentColumnsExpanded: [
      { name: "foreign_urgent_batch_id", label: "Foreign Urgent Batch ID" },
      { name: "batch_id", label: "Parent Batch ID" },
      { name: "patient_name", label: "Patient Name" },
      { name: "medical_aid_nr", label: "Medical Aid Number" },
      { name: "current_department", label: "Current Department" },
      { name: "status", label: "Status" },
      { name: "created_by", label: "Created By", formatter: (val, row) => row.created_by_name ?? val },
      { name: "admitted_by", label: "Admitted By", formatter: (val, row) => row.admitted_by_name ?? val },
      { name: "billed_by", label: "Billed By", formatter: (val, row) => row.billed_by_name ?? val },
      { name: "completed_by", label: "Completed By" },
      { name: "date_checked", label: "Date Checked", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "checked_by", label: "Checked By" },
      { name: "errors", label: "Errors" },
      { name: "file_renamed", label: "File Renamed", formatter: (val) => (val ? "Yes" : "No") },
      { name: "file_renamed_by", label: "File Renamed By" },
      { name: "file_checked", label: "File Checked", formatter: (val) => (val ? "Yes" : "No") },
      { name: "file_checked_by", label: "File Checked By" },
      { name: "filed_by", label: "Filed By" },
      { name: "notes", label: "Notes" },
      { name: "FULID", label: "FULID" },
      { name: "created_at", label: "Created At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "updated_at", label: "Updated At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      // Inherited from batches
      { name: "client_id", label: "Client", formatter: (val, row) => (row.client_first || row.client_last) ? (`Dr ${row.client_first || ''} ${row.client_last || ''}`).trim() : val },
      { name: "method_received", label: "Method Received" },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "bank_statements", label: "Bank Statements", formatter: (val) => (val ? "Yes" : "No") },
      { name: "added_on_drive", label: "Added on Drive", formatter: (val) => (val ? "Yes" : "No") },
      { name: "cc_availability", label: "CC Availability" },
      { name: "corrections", label: "Corrections", formatter: (val) => (val ? "Yes" : "No") },
    ],
     // Archives a batch -> for now, lets just delete the workflow row thus removing it from the workflow views
    filingActions: [
      {
        name: "archive",
        label: "Archive",
        method: "post",
        endpointKey: "archiveBatch",
      },
    ],
    // Accepts the batch into the department
    inboxActions: [
      {
        name: "accept",
        label: "Accept",
        method: "post",
        endpointKey: "acceptBatch",
      },
    ],
    // Pull back the batch from the outbox back to current
    outboxActions: [
      {
        name: "cancelTransfer",
        label: "Cancel Transfer",
        method: "post",
        endpointKey: "pullbackBatch",
      },
    ],
    // Actions available in expanded batch view
    expandedActions: [
      {
        name: "sentToBilling",
        label: "Send to Billing",
        method: "post",
        endpointKey: "moveToBilling",
      },
      {
        name: "sentToAdmittance",
        label: "Send to Admittance",
        method: "post",
        endpointKey: "moveToAdmittance",
      },
    ],
    // Main action available in expanded batch view
    expandedActionsMain: [
      {
        name: "sentToAdmittance",
        label: "Send to Admittance",
        method: "post",
        endpointKey: "moveToAdmittance",
      },
    ],
    tables: [
      { name: "inbox" },
      { name: "current" },
      { name: "outbox" },
      { name: "filing" },
    ],
  },
  admittance: {
    socketRoom: "admittance",
    endpointKey: "admittanceWorkflow",
    columns: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client", formatter: (val, row) => (row.client_first || row.client_last) ? (`Dr ${row.client_first || ''} ${row.client_last || ''}`).trim() : val },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "method_received", label: "Method Received" },
    ],
    columnsExpanded: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client", formatter: (val, row) => (row.client_first || row.client_last) ? (`Dr ${row.client_first || ''} ${row.client_last || ''}`).trim() : val },
      { name: "batch_size", label: "Batch Size" },
      { name: "method_received", label: "Method Received" },
      { name: "bank_statements", label: "Bank Statements", formatter: (val) => (val ? "Yes" : "No") },
      { name: "synaps", label: "Synaps" },
      { name: "total_urgent_foreign", label: "Total Urgent Foreign" },
      { name: "cc_availability", label: "CC Availability" },
      { name: "current_department", label: "Current Department" },
      { name: "status", label: "Status" },
      { name: "batch_total", label: "Batch Total", formatter: (val) => formatCurrency(val) },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "date_completed", label: "Date Completed", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "created_by", label: "Created By", formatter: (val, row) => row.created_by_name ?? val },
      { name: "admitted_by", label: "Admitted By", formatter: (val, row) => row.admitted_by_name ?? val },
      { name: "billed_by", label: "Billed By", formatter: (val, row) => row.billed_by_name ?? val },
      { name: "completed_by", label: "Completed By" },
      { name: "date_checked", label: "Date Checked", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "checked_by", label: "Checked By" },
      { name: "errors", label: "Errors" },
      { name: "billing_emailed_by", label: "Billing Emailed By" },
      { name: "file_renamed_by", label: "File Renamed By" },
      { name: "file_checked_by", label: "File Checked By" },
      { name: "filed_by", label: "Filed By" },
      { name: "notes", label: "Notes" },
      { name: "billing_email_sent_by", label: "Billing Email Sent By" },
      { name: "added_on_drive", label: "Added on Drive", formatter: (val) => (val ? "Yes" : "No") },
      { name: "corrections", label: "Corrections", formatter: (val) => (val ? "Yes" : "No") },
      { name: "is_pure_foreign_urgent", label: "Is Pure Foreign Urgent", formatter: (val) => (val ? "Yes" : "No") },
      { name: "created_at", label: "Created At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "updated_at", label: "Updated At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
    ],
    foreignUrgentColumns: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client", formatter: (val, row) => (row.client_first || row.client_last) ? (`Dr ${row.client_first || ''} ${row.client_last || ''}`).trim() : val },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "method_received", label: "Method Received" },
      { name: "patient_name", label: "Patient Name" },
      { name: "medical_aid_nr", label: "Medical Aid Number" },
    ],
    foreignUrgentColumnsExpanded: [
      { name: "foreign_urgent_batch_id", label: "Foreign Urgent Batch ID" },
      { name: "batch_id", label: "Parent Batch ID" },
      { name: "patient_name", label: "Patient Name" },
      { name: "medical_aid_nr", label: "Medical Aid Number" },
      { name: "current_department", label: "Current Department" },
      { name: "status", label: "Status" },
      { name: "created_by", label: "Created By", formatter: (val, row) => row.created_by_name ?? val },
      { name: "admitted_by", label: "Admitted By", formatter: (val, row) => row.admitted_by_name ?? val },
      { name: "billed_by", label: "Billed By", formatter: (val, row) => row.billed_by_name ?? val },
      { name: "completed_by", label: "Completed By" },
      { name: "date_checked", label: "Date Checked", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "checked_by", label: "Checked By" },
      { name: "errors", label: "Errors" },
      { name: "file_renamed", label: "File Renamed", formatter: (val) => (val ? "Yes" : "No") },
      { name: "file_renamed_by", label: "File Renamed By" },
      { name: "file_checked", label: "File Checked", formatter: (val) => (val ? "Yes" : "No") },
      { name: "file_checked_by", label: "File Checked By" },
      { name: "filed_by", label: "Filed By" },
      { name: "notes", label: "Notes" },
      { name: "FULID", label: "FULID" },
      { name: "created_at", label: "Created At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "updated_at", label: "Updated At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "client_id", label: "Client", formatter: (val, row) => (row.client_first || row.client_last) ? (`Dr ${row.client_first || ''} ${row.client_last || ''}`).trim() : val },
      { name: "method_received", label: "Method Received" },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "bank_statements", label: "Bank Statements", formatter: (val) => (val ? "Yes" : "No") },
      { name: "added_on_drive", label: "Added on Drive", formatter: (val) => (val ? "Yes" : "No") },
      { name: "cc_availability", label: "CC Availability" },
      { name: "corrections", label: "Corrections", formatter: (val) => (val ? "Yes" : "No") },
    ],
    // Accepts the batch into the department
    inboxActions: [
      {
        name: "accept",
        label: "Accept",
        method: "post",
        endpointKey: "acceptBatch",
      },
    ],
    // Pull back the batch from the outbox back to current
    outboxActions: [
      {
        name: "cancelTransfer",
        label: "Cancel Transfer",
        method: "post",
        endpointKey: "pullbackBatch",
      },
    ],
    // Actions available in expanded batch view
    expandedActions: [
      {
        name: "sentToReception",
        label: "Send to Reception",
        method: "post",
        endpointKey: "moveToReception",
      },
    ],
    // Main action available in expanded batch view
    expandedActionsMain: [
      {
        name: "sentToBilling",
        label: "Send to Billing",
        method: "post",
        endpointKey: "moveToBilling",
      },
    ],
    tables: [
      { name: "inbox" },
      { name: "current" },
      { name: "outbox" },
    ],
  },
  billing: {
    socketRoom: "billing",
    endpointKey: "billingWorkflow",
    columns: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client", formatter: (val, row) => (row.client_first || row.client_last) ? (`Dr ${row.client_first || ''} ${row.client_last || ''}`).trim() : val },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "method_received", label: "Method Received" },
    ],
    columnsExpanded: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client", formatter: (val, row) => (row.client_first || row.client_last) ? (`Dr ${row.client_first || ''} ${row.client_last || ''}`).trim() : val },
      { name: "batch_size", label: "Batch Size" },
      { name: "method_received", label: "Method Received" },
      { name: "bank_statements", label: "Bank Statements", formatter: (val) => (val ? "Yes" : "No") },
      { name: "synaps", label: "Synaps" },
      { name: "total_urgent_foreign", label: "Total Urgent Foreign" },
      { name: "cc_availability", label: "CC Availability" },
      { name: "current_department", label: "Current Department" },
      { name: "status", label: "Status" },
      { name: "batch_total", label: "Batch Total", formatter: (val) => formatCurrency(val) },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "date_completed", label: "Date Completed", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "created_by", label: "Created By", formatter: (val, row) => row.created_by_name ?? val },
      { name: "admitted_by", label: "Admitted By", formatter: (val, row) => row.admitted_by_name ?? val },
      { name: "billed_by", label: "Billed By", formatter: (val, row) => row.billed_by_name ?? val },
      { name: "completed_by", label: "Completed By" },
      { name: "date_checked", label: "Date Checked", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "checked_by", label: "Checked By" },
      { name: "errors", label: "Errors" },
      { name: "billing_emailed_by", label: "Billing Emailed By" },
      { name: "file_renamed_by", label: "File Renamed By" },
      { name: "file_checked_by", label: "File Checked By" },
      { name: "filed_by", label: "Filed By" },
      { name: "notes", label: "Notes" },
      { name: "billing_email_sent_by", label: "Billing Email Sent By" },
      { name: "added_on_drive", label: "Added on Drive", formatter: (val) => (val ? "Yes" : "No") },
      { name: "corrections", label: "Corrections", formatter: (val) => (val ? "Yes" : "No") },
      { name: "is_pure_foreign_urgent", label: "Is Pure Foreign Urgent", formatter: (val) => (val ? "Yes" : "No") },
      { name: "created_at", label: "Created At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "updated_at", label: "Updated At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
    ],
    foreignUrgentColumns: [
      { name: "batch_id", label: "Batch ID" },
      { name: "client_id", label: "Client", formatter: (val, row) => (row.client_first || row.client_last) ? (`Dr ${row.client_first || ''} ${row.client_last || ''}`).trim() : val },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "method_received", label: "Method Received" },
      { name: "patient_name", label: "Patient Name" },
      { name: "medical_aid_nr", label: "Medical Aid Number" },
    ],
    foreignUrgentColumnsExpanded: [
      { name: "foreign_urgent_batch_id", label: "Foreign Urgent Batch ID" },
      { name: "batch_id", label: "Parent Batch ID" },
      { name: "patient_name", label: "Patient Name" },
      { name: "medical_aid_nr", label: "Medical Aid Number" },
      { name: "current_department", label: "Current Department" },
      { name: "status", label: "Status" },
      { name: "created_by", label: "Created By", formatter: (val, row) => row.created_by_name ?? val },
      { name: "admitted_by", label: "Admitted By", formatter: (val, row) => row.admitted_by_name ?? val },
      { name: "billed_by", label: "Billed By", formatter: (val, row) => row.billed_by_name ?? val },
      { name: "completed_by", label: "Completed By" },
      { name: "date_checked", label: "Date Checked", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "checked_by", label: "Checked By" },
      { name: "errors", label: "Errors" },
      { name: "file_renamed", label: "File Renamed", formatter: (val) => (val ? "Yes" : "No") },
      { name: "file_renamed_by", label: "File Renamed By" },
      { name: "file_checked", label: "File Checked", formatter: (val) => (val ? "Yes" : "No") },
      { name: "file_checked_by", label: "File Checked By" },
      { name: "filed_by", label: "Filed By" },
      { name: "notes", label: "Notes" },
      { name: "FULID", label: "FULID" },
      { name: "created_at", label: "Created At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "updated_at", label: "Updated At", formatter: (val) => (val ? new Date(val).toLocaleString() : "") },
      { name: "client_id", label: "Client", formatter: (val, row) => (row.client_first || row.client_last) ? (`Dr ${row.client_first || ''} ${row.client_last || ''}`).trim() : val },
      { name: "method_received", label: "Method Received" },
      { name: "date_received", label: "Date Received", formatter: (val) => (val ? new Date(val).toLocaleDateString() : "") },
      { name: "bank_statements", label: "Bank Statements", formatter: (val) => (val ? "Yes" : "No") },
      { name: "added_on_drive", label: "Added on Drive", formatter: (val) => (val ? "Yes" : "No") },
      { name: "cc_availability", label: "CC Availability" },
      { name: "corrections", label: "Corrections", formatter: (val) => (val ? "Yes" : "No") },
    ],
    // Accepts the batch into the department
    inboxActions: [
      {
        name: "accept",
        label: "Accept",
        method: "post",
        endpointKey: "acceptBatch",
      },
    ],
    // Pull back the batch from the outbox back to current
    outboxActions: [
      {
        name: "cancelTransfer",
        label: "Cancel Transfer",
        method: "post",
        endpointKey: "pullbackBatch",
      },
    ],
    // Actions available in expanded batch view
    expandedActions: [
      {
        name: "sentToReception",
        label: "Send to Reception",
        method: "post",
        endpointKey: "moveToReception",
      },
      {
        name: "sentToAdmittance",
        label: "Send to Admittance",
        method: "post",
        endpointKey: "moveToAdmittance",
      },
    ],
    // Main action available in expanded batch view
    expandedActionsMain: [
      {
        name: "sentToFiling",
        label: "Send to Filing",
        method: "post",
        endpointKey: "moveToFiling",
      },
    ],
    tables: [
      { name: "inbox" },
      { name: "current" },
      { name: "outbox" },
      // future: { name: "filing" }, { name: "archived" },
    ],
  },
};

export default WORKFLOW_CONFIG;


